server: 
  port: 8082

####### resource server configuration properties
spring:
  webflux:
    base-path: /resource-server
  jpa:
    defer-datasource-initialization: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/springdoc
          jwk-set-uri: http://localhost:8083/auth/realms/springdoc/protocol/openid-connect/certs
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    oauth:
      clientId: newClient
      clientSecret: newClientSecret
  oAuthFlow:
    authorizationUrl: http://localhost:8083/auth/realms/springdoc/protocol/openid-connect/auth
    tokenUrl: http://localhost:8083/auth/realms/springdoc/protocol/openid-connect/token
